<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Saanchi Shah; UID = 204591578">

<title>Biostat 203B Homework 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="shah_saanchi_hw1solution_files/libs/clipboard/clipboard.min.js"></script>
<script src="shah_saanchi_hw1solution_files/libs/quarto-html/quarto.js"></script>
<script src="shah_saanchi_hw1solution_files/libs/quarto-html/popper.min.js"></script>
<script src="shah_saanchi_hw1solution_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="shah_saanchi_hw1solution_files/libs/quarto-html/anchor.min.js"></script>
<link href="shah_saanchi_hw1solution_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="shah_saanchi_hw1solution_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="shah_saanchi_hw1solution_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="shah_saanchi_hw1solution_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="shah_saanchi_hw1solution_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#q1.-gitgithub" id="toc-q1.-gitgithub" class="nav-link active" data-scroll-target="#q1.-gitgithub"><span class="toc-section-number">1</span>  Q1. Git/GitHub</a></li>
  <li><a href="#q2.-data-ethics-training" id="toc-q2.-data-ethics-training" class="nav-link" data-scroll-target="#q2.-data-ethics-training"><span class="toc-section-number">2</span>  Q2. Data ethics training</a></li>
  <li><a href="#q3.-linux-shell-commands" id="toc-q3.-linux-shell-commands" class="nav-link" data-scroll-target="#q3.-linux-shell-commands"><span class="toc-section-number">3</span>  Q3. Linux Shell Commands</a></li>
  <li><a href="#q4.-whos-popular-in-price-and-prejudice" id="toc-q4.-whos-popular-in-price-and-prejudice" class="nav-link" data-scroll-target="#q4.-whos-popular-in-price-and-prejudice"><span class="toc-section-number">4</span>  Q4. Who’s popular in Price and Prejudice</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 203B Homework 1</h1>
<p class="subtitle lead">Due Jan 27 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Saanchi Shah; UID = 204591578 </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Display machine information for reproducibility:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.30     jsonlite_1.8.3    magrittr_2.0.3    evaluate_0.17    
 [5] rlang_1.0.6       stringi_1.7.8     cli_3.4.1         rstudioapi_0.14  
 [9] rmarkdown_2.17    tools_4.2.2       stringr_1.4.1     htmlwidgets_1.5.4
[13] xfun_0.34         yaml_2.3.6        fastmap_1.1.0     compiler_4.2.2   
[17] htmltools_0.5.3   knitr_1.40       </code></pre>
</div>
</div>
<section id="q1.-gitgithub" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="q1.-gitgithub"><span class="header-section-number">1</span> Q1. Git/GitHub</h2>
<p>There were no questions in this section. This section instructed us to create our repo and store files appropriately.</p>
</section>
<section id="q2.-data-ethics-training" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="q2.-data-ethics-training"><span class="header-section-number">2</span> Q2. Data ethics training</h2>
<ol type="1">
<li><p>This is a link to <a href="https://www.citiprogram.org/verify/?w1305913e-39b4-46d7-8c1c-3d368d0a2560-53778952">CITI Certificate</a></p></li>
<li><p>This is a link to <a href="https://citiprogram.org/verify/?kc4b3b566-f3cb-422e-8cbf-48e53713387c-53778952">CITI Report</a></p></li>
</ol>
</section>
<section id="q3.-linux-shell-commands" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="q3.-linux-shell-commands"><span class="header-section-number">3</span> Q3. Linux Shell Commands</h2>
<ol type="1">
<li>The <code>~/mimic</code> folder within the Docker container contains data sets from MIMIC-IV. Refer to the documentation <a href="https://mimic.mit.edu/docs/iv/" class="uri">https://mimic.mit.edu/docs/iv/</a> for details of data files.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Use Bash commands to answer following questions.</p>
<ol start="2" type="1">
<li>Display the contents in the folders <code>core</code>, <code>hosp</code>, <code>icu</code>. Why are these data files distributed as <code>.csv.gz</code> files instead of <code>.csv</code> (comma separated values) files? Read the page <a href="https://mimic.mit.edu/docs/iv/" class="uri">https://mimic.mit.edu/docs/iv/</a> to understand what’s in each folder.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/core</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/hosp</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/icu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total 142944
-rw-rw-r--@ 1 saanchishah  staff  17208966 Mar 15  2021 admissions.csv.gz
-rw-rw-r--@ 1 saanchishah  staff       606 Jan  4  2022 index.html
-rw-rw-r--@ 1 saanchishah  staff   2955582 Mar 15  2021 patients.csv.gz
-rw-rw-r--@ 1 saanchishah  staff  53014503 Mar 15  2021 transfers.csv.gz
total 9243184
-rw-rw-r--@ 1 saanchishah  staff      430049 Mar 15  2021 d_hcpcs.csv.gz
-rw-rw-r--@ 1 saanchishah  staff      863239 Mar 15  2021 d_icd_diagnoses.csv.gz
-rw-rw-r--@ 1 saanchishah  staff      579998 Mar 15  2021 d_icd_procedures.csv.gz
-rw-rw-r--@ 1 saanchishah  staff       14898 Mar 15  2021 d_labitems.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    29531152 Mar 15  2021 diagnoses_icd.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    11684062 Mar 15  2021 drgcodes.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   515763427 Mar 15  2021 emar.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   476252563 Mar 15  2021 emar_detail.csv.gz
-rw-rw-r--@ 1 saanchishah  staff     2098831 Mar 15  2021 hcpcsevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff        2325 Jan  4  2022 index.html
-rw-rw-r--@ 1 saanchishah  staff  2091865786 Mar 15  2021 labevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   171624288 Jan 27  2022 labevents_filtered_itemid.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    99133381 Mar 15  2021 microbiologyevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   422874088 Mar 15  2021 pharmacy.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   501381155 Mar 15  2021 poe.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    24020923 Mar 15  2021 poe_detail.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   367041717 Mar 15  2021 prescriptions.csv.gz
-rw-rw-r--@ 1 saanchishah  staff     7750325 Mar 15  2021 procedures_icd.csv.gz
-rw-rw-r--@ 1 saanchishah  staff     9565293 Mar 15  2021 services.csv.gz
total 5698008
-rw-rw-r--@ 1 saanchishah  staff  2350783547 Mar 15  2021 chartevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff   110272408 Jan 27  2022 chartevents_filtered_itemid.csv.gz
-rw-rw-r--@ 1 saanchishah  staff       55917 Mar 15  2021 d_items.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    43296273 Mar 15  2021 datetimeevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff     2848628 Mar 15  2021 icustays.csv.gz
-rw-rw-r--@ 1 saanchishah  staff        1103 Jan  4  2022 index.html
-rw-rw-r--@ 1 saanchishah  staff   352443512 Mar 15  2021 inputevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    37095672 Mar 15  2021 outputevents.csv.gz
-rw-rw-r--@ 1 saanchishah  staff    20567368 Mar 15  2021 procedureevents.csv.gz</code></pre>
</div>
</div>
<p>Answer: The data files are distributed as .csv.gz because these are such huge datasets that it helps with space conservation/reduction. It’s also easier to read and write the files and does not need us to decompress the files, thereby, saving us some time in writing additional steps or performing additional unzipping and saving commands/steps.</p>
<ol start="3" type="1">
<li>Briefly describe what bash commands <code>zcat</code>, <code>zless</code>, <code>zmore</code>, and <code>zgrep</code> do.</li>
</ol>
<p>Answer: All of these commands are similar to cat, less, more, grep respectively, however, they can handle compressed files in the gzip format which is why we can use these commands for the mimic folder contents as we will not be decompressing the files. 1. For example, Zcat displays the contents of the admissions.csv.gz file 2. For example, zless helps us view the contents of the admissions.csv.gz file one page at a time. In class we discussed that less is more powerful than more and my sense is that zless is more powerful than zmore because it loads files faster than more/zmore. 3. zmore more browses a gzip file screen by screen (only downwards) akin to the more command. 4. zgrep prints lines that match an expression in the gzip compressed files. The beauty of all of these commands is that one need not decompress the gzip files which saves a lot of space.</p>
<ol start="4" type="1">
<li>What’s the output of the following bash script?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/core/<span class="pp">*</span>.gz</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ls</span> <span class="at">-l</span> <span class="va">$datafile</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of the provided bash script is as follows: Show in New Window total 142944 -rw-rw-r–@ 1 saanchishah staff 17208966 Mar 15 2021 admissions.csv.gz -rw-rw-r–@ 1 saanchishah staff 606 Jan 4 2022 index.html -rw-rw-r–@ 1 saanchishah staff 2955582 Mar 15 2021 patients.csv.gz -rw-rw-r–@ 1 saanchishah staff 53014503 Mar 15 2021 transfers.csv.gz Show in New Window total 24 -rw-rw-r–@ 1 saanchishah staff 2518 Mar 10 2021 LICENSE.txt drwxr-xr-x@ 5 saanchishah staff 160 Jan 25 15:06 MIMIC-reduce-chartevents -rw-rw-r–@ 1 saanchishah staff 2459 Mar 16 2021 SHA256SUMS.txt drwxr-xr-x@ 6 saanchishah staff 192 Jan 25 15:06 core drwxr-xr-x@ 21 saanchishah staff 672 Jan 25 15:06 hosp drwxr-xr-x@ 11 saanchishah staff 352 Jan 25 15:06 icu -rw-rw-r–@ 1 saanchishah staff 797 Jan 4 2022 index.html Show in New Window -rw-rw-r–@ 1 saanchishah staff 17208966 Mar 15 2021 /Users/saanchishah/mimic/mimic-iv-1.0/core/admissions.csv.gz -rw-rw-r–@ 1 saanchishah staff 2955582 Mar 15 2021 /Users/saanchishah/mimic/mimic-iv-1.0/core/patients.csv.gz -rw-rw-r–@ 1 saanchishah staff 53014503 Mar 15 2021 /Users/saanchishah/mimic/mimic-iv-1.0/core/transfers.csv.gz</p>
<p>Display the number of lines in each data file using a similar loop.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/core/<span class="pp">*</span>.gz</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> <span class="va">$datafile</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  523741
  382279
 2189536</code></pre>
</div>
</div>
<p>The 3 datafiles in the core directory (admissions.csv.gz, patients.csv.gz, transfers.csv.gz) have 523741, 382279, 2189536</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/hosp/<span class="pp">*</span>.gz</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> <span class="va">$datafile</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   89201
  109776
   85258
    1631
 5280352
  769623
 27464368
 55947924
  160728
 122103668
 30198827
 3397915
 14736387
 42483963
 3256359
 17008054
  779626
  562893</code></pre>
</div>
</div>
<p>This code chunk displays the number of lines for each of the 18 files in the ‘hosp’ directory.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/icu/<span class="pp">*</span>.gz</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> <span class="va">$datafile</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span>   </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 329499789
 23679059
    3862
 7495713
   76541
 9460659
 4457382
  731248</code></pre>
</div>
</div>
<p>This code chunk helps display the number of lines in each datafile in the icu directory.</p>
<p>The below alternate code does a double loop to count the number of lines in all the datafiles in all the folders.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> folder <span class="kw">in</span> core hosp icu</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="va">$folder</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/<span class="va">$folder</span>/<span class="pp">*</span>.gz</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="va">$datafile</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> <span class="va">$datafile</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>core
/Users/saanchishah/mimic/core/admissions.csv.gz
  523741
/Users/saanchishah/mimic/core/patients.csv.gz
  382279
/Users/saanchishah/mimic/core/transfers.csv.gz
 2189536
hosp
/Users/saanchishah/mimic/hosp/d_hcpcs.csv.gz
   89201
/Users/saanchishah/mimic/hosp/d_icd_diagnoses.csv.gz
  109776
/Users/saanchishah/mimic/hosp/d_icd_procedures.csv.gz
   85258
/Users/saanchishah/mimic/hosp/d_labitems.csv.gz
    1631
/Users/saanchishah/mimic/hosp/diagnoses_icd.csv.gz
 5280352
/Users/saanchishah/mimic/hosp/drgcodes.csv.gz
  769623
/Users/saanchishah/mimic/hosp/emar.csv.gz
 27464368
/Users/saanchishah/mimic/hosp/emar_detail.csv.gz
 55947924
/Users/saanchishah/mimic/hosp/hcpcsevents.csv.gz
  160728
/Users/saanchishah/mimic/hosp/labevents.csv.gz
 122103668
/Users/saanchishah/mimic/hosp/labevents_filtered_itemid.csv.gz
 30198827
/Users/saanchishah/mimic/hosp/microbiologyevents.csv.gz
 3397915
/Users/saanchishah/mimic/hosp/pharmacy.csv.gz
 14736387
/Users/saanchishah/mimic/hosp/poe.csv.gz
 42483963
/Users/saanchishah/mimic/hosp/poe_detail.csv.gz
 3256359
/Users/saanchishah/mimic/hosp/prescriptions.csv.gz
 17008054
/Users/saanchishah/mimic/hosp/procedures_icd.csv.gz
  779626
/Users/saanchishah/mimic/hosp/services.csv.gz
  562893
icu
/Users/saanchishah/mimic/icu/chartevents.csv.gz
 329499789
/Users/saanchishah/mimic/icu/chartevents_filtered_itemid.csv.gz
 23679059
/Users/saanchishah/mimic/icu/d_items.csv.gz
    3862
/Users/saanchishah/mimic/icu/datetimeevents.csv.gz
 7495713
/Users/saanchishah/mimic/icu/icustays.csv.gz
   76541
/Users/saanchishah/mimic/icu/inputevents.csv.gz
 9460659
/Users/saanchishah/mimic/icu/outputevents.csv.gz
 4457382
/Users/saanchishah/mimic/icu/procedureevents.csv.gz
  731248</code></pre>
</div>
</div>
<p>This is an alternative method to count the number of non-blank rows only.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/core/<span class="pp">*</span>.gz</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="st">'END { print NR }'</span> <span class="va">$datafile</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>66156
8713
197787</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Display the first few lines of <code>admissions.csv.gz</code>. How many rows are in this data file? How many unique patients (identified by <code>subject_id</code>) are in this data file? (Hint: combine Linux commands <code>zcat</code>, <code>head</code>/<code>tail</code>, <code>awk</code>, <code>sort</code>, <code>uniq</code>, <code>wc</code>, and so on.)</li>
</ol>
<p>Displaying the number of first few lines of ‘admissions.csv.gz’ #gunzip -c ~/mimic/core/admissions.csv.gz | head -n 10 # This command works #perfectly fine in terminal but not in R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"The first few lines of admissions.csv.gz are:"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">zcat</span> <span class="op">&lt;</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">head</span> <span class="at">-n</span> 10 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The first few lines of admissions.csv.gz are:
subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0
15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
11989120,21965160,2147-01-14 09:00:00,2147-01-17 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0
17817079,24709883,2165-12-27 17:33:00,2165-12-31 21:18:00,,ELECTIVE,,HOME,Other,ENGLISH,,OTHER,,,0
15078341,23272159,2122-08-28 08:48:00,2122-08-30 12:32:00,,ELECTIVE,,HOME,Other,ENGLISH,,BLACK/AFRICAN AMERICAN,,,0
19124609,20517215,2169-03-14 12:44:00,2169-03-20 19:15:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0
17301855,29732723,2140-06-06 14:23:00,2140-06-08 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
17991012,24298836,2181-07-10 20:28:00,2181-07-12 15:49:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
16865435,23216961,2185-07-19 02:12:00,2185-07-21 11:50:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0</code></pre>
</div>
</div>
<p>This works perfectly fine on terminal but not as well in R</p>
<p>#Display number of rows in the admissions.csv.gz datafile</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">" The number of rows in this file are:"</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">zcat</span> <span class="op">&lt;</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> The number of rows in this file are:
  523741</code></pre>
</div>
</div>
<p>There are 523741 rows in this file</p>
<p>Display number of unique patient ids in this datafile</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="at">-c</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-F,</span> <span class="st">'{print $1}'</span><span class="dt">\</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  256879</code></pre>
</div>
</div>
<p>Or this also works #gunzip -c ~/mimic/core/admissions.csv.gz | awk -F, ‘{unique[$1]++} END {for (i in unique) print i}’ | wc -l Answer: There are 256879 unique ids in this file. First, I unzipped the file, then I piped it to filter by the separator “,” to look through the first parameter/variable which is subject_id. Then I sorted the ids, used the command uniq to display unique ids and then piped it to get a count of ids that show up only once (in other words ids that are unique).</p>
<ol start="6" type="1">
<li>What are the possible values taken by each of the variable <code>admission_type</code>, <code>admission_location</code>, <code>insurance</code>, and <code>ethnicity</code>? Also report the count for each unique value of these variables. (Hint: combine Linux commands <code>zcat</code>, <code>head</code>/<code>tail</code>, <code>awk</code>, <code>uniq -c</code>, <code>wc</code>, and so on.)</li>
</ol>
<p>First, I understood the location of each variable/column # in the file to perform the below code.</p>
<p>Code to derive the possible values taken by admission_type</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="at">-c</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-F</span> <span class="st">","</span> <span class="st">'{if ($6 !="admission_type") print $6}'</span><span class="dt">\</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7254 AMBULATORY OBSERVATION
21581 DIRECT EMER.
19991 DIRECT OBSERVATION
72072 ELECTIVE
100445 EU OBSERVATION
157896 EW EMER.
55497 OBSERVATION ADMIT
41074 SURGICAL SAME DAY ADMISSION
47930 URGENT</code></pre>
</div>
</div>
<p>Answer: The possible values for admission_type are ambulatory observation, direct emer., diect observation, elective, eu observation, ew emer., observation admit, surgical same day admission, urgent</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="at">-c</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-F</span> <span class="st">","</span> <span class="st">'{if($7 !="admission_location") print $7}'</span><span class="dt">\</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>60435 
 191 AMBULATORY SURGERY TRANSFER
10670 CLINIC REFERRAL
245744 EMERGENCY ROOM
 379 INFORMATION NOT AVAILABLE
4467 INTERNAL TRANSFER TO OR FROM PSYCH
6067 PACU
127494 PHYSICIAN REFERRAL
8449 PROCEDURE SITE
39121 TRANSFER FROM HOSPITAL
4063 TRANSFER FROM SKILLED NURSING FACILITY
16660 WALK-IN/SELF REFERRAL</code></pre>
</div>
</div>
<p>Answer: admission_location take on the values such as ambulatory surgery transfer, clinic referral, clinic referral, emergency room, information not available, internal transfer to or from psych, pacu, physician referral, procedure site, transfer from hospital, transfer from skilled nursing facility, walk-in/self referral</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="at">-c</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-F</span> <span class="st">","</span> <span class="st">'{if ($9 !="insurance")print $9}'</span><span class="dt">\</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>50850 Medicaid
171360 Medicare
301530 Other</code></pre>
</div>
</div>
<p>Answer: Insurance takes on the value of Medicaid, Medicare and Other</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="at">-c</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-F</span> <span class="st">","</span> <span class="st">'{if ($12 !="ethnicity")print $12}'</span><span class="dt">\</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1535 AMERICAN INDIAN/ALASKA NATIVE
24506 ASIAN
80293 BLACK/AFRICAN AMERICAN
29823 HISPANIC/LATINO
26813 OTHER
3740 UNABLE TO OBTAIN
19400 UNKNOWN
337630 WHITE</code></pre>
</div>
</div>
<p>Answer: Ethnicity takes on the values of American Indian/Alaska native, Asian, Black/African American, Hispanic/Latino, Other, Unable to obtain, unknown, white</p>
</section>
<section id="q4.-whos-popular-in-price-and-prejudice" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="q4.-whos-popular-in-price-and-prejudice"><span class="header-section-number">4</span> Q4. Who’s popular in Price and Prejudice</h2>
<ol type="1">
<li>You and your friend just have finished reading <em>Pride and Prejudice</em> by Jane Austen. Among the four main characters in the book, Elizabeth, Jane, Lydia, and Darcy, your friend thinks that Darcy was the most mentioned. You, however, are certain it was Elizabeth. Obtain the full text of the novel from <a href="http://www.gutenberg.org/cache/epub/42671/pg42671.txt" class="uri">http://www.gutenberg.org/cache/epub/42671/pg42671.txt</a> and save to your local folder.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-L</span> <span class="at">-O</span> http://www.gutenberg.org/cache/epub/42671/pg42671.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Answer: wget did not work for me so I used, curl. This command helped download a file from a web server.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> char <span class="kw">in</span> Elizabeth Jane Lydia Darcy<span class="kw">;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span> <span class="bu">echo</span> <span class="va">$char</span>:<span class="kw">;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span> <span class="at">-o</span> <span class="at">-i</span> <span class="va">$char</span> pg42671.txt <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-w</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Elizabeth:
     634
Jane:
     294
Lydia:
     171
Darcy:
     418</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>What’s the difference between the following two commands?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">'hello, world'</span> <span class="op">&gt;</span> test1.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">'hello, world'</span> <span class="op">&gt;&gt;</span> test2.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Answer: While there is a difference between using the ‘&gt;’ and ‘&gt;&gt;’ commands because the former will overwrite the output of the file and the latter will append to the existing output of a file, we get a similar result because these files did not originally exist. Both test1 and test2 appear same because both the files contain the following text ‘hello, world’ since these were new files created by each of the commands we entered.</p>
<ol start="3" type="1">
<li>Using your favorite text editor (e.g., <code>vi</code>), type the following and save the file as <code>middle.sh</code>:</li>
</ol>
<p>I used terminal ad entered the following: vi middle sh.</p>
<p>Then I copied the below code in the text editor, clicked on the escape button, typed :wq to save and exit out of the editor.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#!/bin/sh</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select lines from the middle of a file.</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Usage: bash middle.sh filename end_line num_lines</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> <span class="at">-n</span> <span class="st">"</span><span class="va">$2</span><span class="st">"</span> <span class="st">"</span><span class="va">$1</span><span class="st">"</span> <span class="kw">|</span> <span class="fu">tail</span> <span class="at">-n</span> <span class="st">"</span><span class="va">$3</span><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using <code>chmod</code> to make the file executable by the owner, and run #code #chmod 700 middle.sh</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ./hw1</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="ex">./middle.sh</span> pg42671.txt 20 5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explain the output. Explain the meaning of <code>"$1"</code>, <code>"$2"</code>, and <code>"$3"</code> in this shell script. Why do we need the first line of the shell script?</p>
<p>Output</p>
<p>Author: Jane Austen</p>
<p>Editor: R. W. (Robert William) Chapman</p>
<p>Explanation of the output: These are command line arguments; special characters $1 is the first argument which is the text file. $2 is 20 which is applied to the novel($1) and then printing the first few lines(head) ending at line 20 and piped to print tail i.e.&nbsp;number of lines to tail = 5. The output includes 5 lines from the text, 3 of which are blank spaces. We did not necessarily need to create middle.sh and could have been achieved by simply printing the text and piping with head and tail arguments by specifying the number of lines. ## Q5. More fun with Linux</p>
<p>Try following commands in Bash and interpret the results: <code>cal</code>, <code>cal 2021</code>, <code>cal 9 1752</code> (anything unusual?), <code>date</code>, <code>hostname</code>, <code>arch</code>, <code>uname -a</code>, <code>uptime</code>, <code>who am i</code>, <code>who</code>, <code>w</code>, <code>id</code>, <code>last | head</code>, <code>echo {con,pre}{sent,fer}{s,ed}</code>, <code>time sleep 5</code>, <code>history | tail</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    January 2023      
Su Mo Tu We Th Fr Sa  
 1  2  3  4  5  6  7  
 8  9 10 11 12 13 14  
15 16 17 18 19 20 21  
22 23 24 25 26 _2_7 28  
29 30 31              
                      </code></pre>
</div>
</div>
<p>Cal shows the calendar for the month January (2023) with today’s date highlighted.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span> 2021 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            2021
      January               February               March          
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                1  2      1  2  3  4  5  6      1  2  3  4  5  6  
 3  4  5  6  7  8  9   7  8  9 10 11 12 13   7  8  9 10 11 12 13  
10 11 12 13 14 15 16  14 15 16 17 18 19 20  14 15 16 17 18 19 20  
17 18 19 20 21 22 23  21 22 23 24 25 26 27  21 22 23 24 25 26 27  
24 25 26 27 28 29 30  28                    28 29 30 31           
31                                                                

       April                  May                   June          
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
             1  2  3                     1         1  2  3  4  5  
 4  5  6  7  8  9 10   2  3  4  5  6  7  8   6  7  8  9 10 11 12  
11 12 13 14 15 16 17   9 10 11 12 13 14 15  13 14 15 16 17 18 19  
18 19 20 21 22 23 24  16 17 18 19 20 21 22  20 21 22 23 24 25 26  
25 26 27 28 29 30     23 24 25 26 27 28 29  27 28 29 30           
                      30 31                                       

        July                 August              September        
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
             1  2  3   1  2  3  4  5  6  7            1  2  3  4  
 4  5  6  7  8  9 10   8  9 10 11 12 13 14   5  6  7  8  9 10 11  
11 12 13 14 15 16 17  15 16 17 18 19 20 21  12 13 14 15 16 17 18  
18 19 20 21 22 23 24  22 23 24 25 26 27 28  19 20 21 22 23 24 25  
25 26 27 28 29 30 31  29 30 31              26 27 28 29 30        
                                                                  

      October               November              December        
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                1  2      1  2  3  4  5  6            1  2  3  4  
 3  4  5  6  7  8  9   7  8  9 10 11 12 13   5  6  7  8  9 10 11  
10 11 12 13 14 15 16  14 15 16 17 18 19 20  12 13 14 15 16 17 18  
17 18 19 20 21 22 23  21 22 23 24 25 26 27  19 20 21 22 23 24 25  
24 25 26 27 28 29 30  28 29 30              26 27 28 29 30 31     
31                                                                </code></pre>
</div>
</div>
<p>The command cal 2021 displays the calendar for the year 2021 (all months January - December).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span> 9 1752 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   September 1752     
Su Mo Tu We Th Fr Sa  
       1  2 14 15 16  
17 18 19 20 21 22 23  
24 25 26 27 28 29 30  
                      
                      
                      </code></pre>
</div>
</div>
<p>This command displays only 19 days under the header “September 1752”, 9 stands for the 9th month and 1752 is the year we want this month’s data to be extracted from. This made no sense to me and I googled the year 1752. It appears that we switched from the Julian calendar to the Gregorian calendar and thus skipped some days.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fri Jan 27 14:42:52 PST 2023</code></pre>
</div>
</div>
<p>This command displayed the day, date and time (hh:mm:ss) per the time zone PST followed by the year.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hostname</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dhcp-10-144-203-43.dgsom.guest</code></pre>
</div>
</div>
<p>I do not entirely understand what dhcps do but I checked the unique ID (network in settings for mac)with my IP address and they’re the same so I believe this is a way to identify my device on any network.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">arch</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>arm64</code></pre>
</div>
</div>
<p>It displays that my CPU has the arm64 architecture.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">uname</span> <span class="at">-a</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Darwin dhcp-10-144-203-43.dgsom.guest 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64</code></pre>
</div>
</div>
<p>I appears that this command lists all the information about my device including kernel version, architecture, unix name, dhcp and so forth.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span> am i</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>saanchis tty??    Jan 27 14:42 </code></pre>
</div>
</div>
<p>This command displayed my username followed by the terminal I am using, today’s date and time (24 hour clock)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Who</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>saanchishah console  Sep  7 23:28 
saanchishah ttys000  Jan 26 21:08 </code></pre>
</div>
</div>
<p>This command displays all users logged in to the machine.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">w</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14:42  up 141 days, 16:14, 2 users, load averages: 6.42 6.13 5.83
USER     TTY      FROM              LOGIN@  IDLE WHAT
saanchishah console  -                07Sep22 141days -
saanchishah s000     -                Thu21   16:56 -zsh          &lt;ff&gt;&lt;bf&gt;    /bin/zsh  </code></pre>
</div>
</div>
<p>This command displays detailed information about all users who are logged in, when they logged in and how long they have been idle.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">last</span> <span class="kw">|</span> <span class="fu">head</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>saanchishah  ttys000                   Thu Jan 26 21:08   still logged in
saanchishah  ttys000                   Thu Jan 26 17:20 - 17:20  (00:00)
saanchishah  ttys004                   Wed Jan 25 18:46 - 18:46  (00:00)
saanchishah  ttys000                   Wed Jan 25 17:23 - 17:23  (00:00)
saanchishah  ttys006                   Wed Jan 25 10:26 - 10:26  (00:00)
saanchishah  ttys000                   Wed Jan 25 10:13 - 10:13  (00:00)
saanchishah  ttys000                   Wed Jan 25 09:56 - 09:56  (00:00)
saanchishah  ttys006                   Tue Jan 24 18:01 - 18:01  (00:00)
saanchishah  ttys000                   Tue Jan 24 18:01 - 18:01  (00:00)
saanchishah  ttys005                   Mon Jan 23 20:19 - 20:19  (00:00)</code></pre>
</div>
</div>
<p>This command last displays all the last logins and piping it with the head command ensures that only the top 10 logins show up.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="dt">{con</span><span class="op">,</span><span class="dt">pre}{sent</span><span class="op">,</span><span class="dt">fer}{s</span><span class="op">,</span><span class="dt">ed}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>consents consented confers confered presents presented prefers prefered</code></pre>
</div>
</div>
<p>This command displays “consents consented confers confered presents presented prefers prefered”. This command seems to concatenate words by using the string ‘con’ which is the first string in the first curly bracket and joins it with the first string of the second bracket followed by the first string of the third bracket = consents. Then ‘con’ runs through the first string of the second bracket followed by the second string of the third bracket = consented. Next, it loops through the second string of the second bracket, followed by the first string of the third bracket = confers. Next, ‘confer’ loops through the second string of the third bracket resulting in ‘confered’. Then the code uses the second string of the first bracket and follows a similar looping pattern.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="bu">time</span> sleep 5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
real    0m5.008s
user    0m0.000s
sys 0m0.002s</code></pre>
</div>
</div>
<p>This command specified that linux should pause for 5 seconds before executing the next command.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="bu">history</span> <span class="kw">|</span> <span class="fu">tail</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This command displayed a history of all commands but since we piped it, it only displayed the last 10 commands typed in terminal.</p>
<p>This is the end of assignment 1. Thank you so much.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>