```{r}
library(shiny)

icu_cohort <- readRDS(file = file.path("/Users/saanchishah/biostat-203b-2023-winter/hw3/mimiciv_shiny", 'icu_cohort.rds'))

head(icu_cohort, n = 5)
icu_cohort_new <- icu_cohort %>% 
  mutate(thirty_day_mortality = if_else(duration < 30, 1, 0)) %>% 
  select(subject_id, stay_id, first_careunit, last_careunit, los, admission_type, 
         insurance, gender, ethnicity, Sodium, Chloride, WBC, Hematocrit, Glucose, 
         Bicarbonate, Creatinine, Potassium, age, thirty_day_mortality, Systolic_BP, 
         Diastolic_BP, Resp_rate, Heart_rate, Temperature)

head(icu_cohort_new, n = 5)

ui <- fluidPage(titlePanel("Saanchi's ICU cohort"),
  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "dataset",
                  label = "Choose a dataset:",
                  choices = "icu_cohort_new"),
      numericInput(inputId = "obs",
                   label = "Number of observations to view:",
                   value = 10)
                   ),
    mainPanel(
      verbatimTextOutput("summary"),
      tableOutput("view"))
    )
  )


# Define server logic to summarize and view selected dataset ----

# define server

server <- function(input, output) {
  # Return the requested dataset ----
  datasetInput <- reactive({
    switch(input$dataset,
           "icu_cohort" = icu_cohort)
  })

  # Generate a summary of the dataset ----
  output$summary <- renderPrint({
    dataset <- datasetInput()
    summary(dataset)
  })

  # Show the first "n" observations ----
  output$view <- renderTable({
    head(datasetInput(), n = input$obs)
  })

}

shinyApp(ui, server)

```



```{r}
# New UI - testing out different variables in here

ui <- fluidPage(titlePanel("Saanchi's ICU cohort"),
  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "Variable",
                  label = "Variable",
                  choices = c("Hematocrit" = "icu_cohort_new$Hematocrit",
                              "Chloride" = "icu_cohort_new$Chloride",
                              "Sodium" = "icu_cohort_new$Sodium",
                              "Potassium" = "icu_cohort_new$Potassium",
                              "WBC" = "icu_cohort_new$WBC",
                              "Glucose" = "icu_cohort_new$Glucose",
                              "Creatinine" ="icu_cohort_new$Creatinine",
                              "Bicarbonate" = "icu_cohort_new$Bicarbonate",
                              "gender" = "icu_cohort_new$gender",
                              "insurance" = "icu_cohort_new$insurance",
                              "ethnicity" = "icu_cohort_new$ethnicity",
                              "age" = "icu_cohort_new$age",
                              "Systolic_BP" = "icu_cohort_new$Systolic_BP",
                              "Diastolic_BP" = "icu_cohort_new$Diastolic_BP",
                              "Resp_rate" = "icu_cohort$Resp_rate",
                              "Heart_rate" = "icu_cohort_new$Heart_rate",
                              "Temperature" = "icu_cohort_new$Temperature",
                              "admission_type" = "icu_cohort_new$admission_type")),
      selectInput("indicator", "Indicator:",
            choices = c("0", "not 0")),
      numericInput(inputId = "obs",
                   label = "Number of observations to view:",
                   value = 10)
                   ),
    mainPanel(
      h2("Numerical and Graphical Summary"),
      verbatimTextOutput("summary"),
      tableOutput("view")
      )
    )
  )



# new server 
server <- function(input, output) {
  # Return the requested dataset ----
  datasetInput <- reactive({
    switch(input$Variable,
           "icu_cohort_new$Hematocrit" = icu_cohort_new$Hematocrit,
           "icu_cohort_new$Chloride" = icu_cohort_new$Chloride,
           "icu_cohort_new$Sodium" = icu_cohort_new$Sodium,
           "icu_cohort_new$Potassium" = icu_cohort_new$Potassium,
           "icu_cohort_new$WBC" = icu_cohort_new$WBC,
           "icu_cohort_new$Glucose" = icu_cohort_new$Glucose,
           "icu_cohort_new$Creatinine" =icu_cohort_new$Creatinine,
           "icu_cohort_new$Bicarbonate" = icu_cohort_new$Bicarbonate,
           "icu_cohort_new$gender" = icu_cohort_new$gender,
           "icu_cohort_new$insurance" = icu_cohort_new$insurance,
           "icu_cohort_new$ethnicity" = icu_cohort_new$ethnicity,
           "icu_cohort_new$age" = icu_cohort_new$age,
           "icu_cohort_new$Systolic_BP" = icu_cohort_new$Systolic_BP,
           "icu_cohort_new$Diastolic_BP" = icu_cohort_new$Diastolic_BP,
           "icu_cohort_new$Resp_rate" = icu_cohort$Resp_rate,
           "icu_cohort_new$Heart_rate" = icu_cohort_new$Heart_rate,
           "icu_cohort_new$Temperature" = icu_cohort_new$Temperature,
           "icu_cohort_new$admission_type" = icu_cohort_new$admission_type
           )
  })

  # select(subject_id, stay_id, first_careunit, last_careunit, los, admission_type, 
  # insurance, gender, ethnicity, Sodium, Chloride, WBC, Hematocrit, Glucose, 
  # Bicarbonate, Creatinine, Potassium, age, thirty_day_mort, Systolic_BP, 
  # Diastolic_BP, Resp_rate, Heart_rate, Temperature)
  
  
  # Generate a summary of the dataset ----
  output$summary <- renderPrint({
    dataset <- datasetInput()
    summary(dataset)
  })

  # Show the first "n" observations ----
  output$view <- renderTable({
    head(datasetInput(), n = input$obs)
  })

}

shinyApp(ui, server)

```


```{r}
head(icu_cohort_new, n =5)

ui <- fluidPage(
  titlePanel("Saanchi's ICU cohort"),
  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "Variable",
        label = "Variable",
        choices = c(
          "Hematocrit" = "icu_cohort_new$Hematocrit",
          "Chloride" = "icu_cohort_new$Chloride",
          "Sodium" = "icu_cohort_new$Sodium",
          "Potassium" = "icu_cohort_new$Potassium",
          "WBC" = "icu_cohort_new$WBC",
          "Glucose" = "icu_cohort_new$Glucose",
          "Creatinine" = "icu_cohort_new$Creatinine",
          "Bicarbonate" = "icu_cohort_new$Bicarbonate",
          "gender" = "icu_cohort_new$gender",
          "insurance" = "icu_cohort_new$insurance",
          "ethnicity" = "icu_cohort_new$ethnicity",
          "age" = "icu_cohort_new$age",
          "Systolic_BP" = "icu_cohort_new$Systolic_BP",
          "Diastolic_BP" = "icu_cohort_new$Diastolic_BP",
          "Resp_rate" = "icu_cohort$Resp_rate",
          "Heart_rate" = "icu_cohort_new$Heart_rate",
          "Temperature" = "icu_cohort_new$Temperature",
          "admission_type" = "icu_cohort_new$admission_type",
          "thirty_day_mortality" = "thirty_day_mortality"
        )
      ),
      selectInput("indicator", "Indicator:", choices = c("0", "1")),
      numericInput(
        inputId = "obs",
        label = "Number of observations to view:",
        value = 10
      )
    ),
    mainPanel(
      h2("Numerical and Graphical Summary"),
      verbatimTextOutput("summary"),
      tableOutput("view"),
      tabsetPanel(tabPanel("Summary", tableOutput("summary")))
    )
  )
)


# new server 
# new server 
server <- function(input, output) {
  # Return the requested dataset ----
  datasetInput <- reactive({
    switch(input$Variable,
           Hematocrit = icu_cohort_new$Hematocrit,
           Chloride = icu_cohort_new$Chloride,
           Sodium = icu_cohort_new$Sodium,
           Potassium = icu_cohort_new$Potassium,
           WBC = icu_cohort_new$WBC,
           Glucose = icu_cohort_new$Glucose,
           Creatinine =icu_cohort_new$Creatinine,
           Bicarbonate = icu_cohort_new$Bicarbonate,
           gender = icu_cohort_new$gender,
           insurance = icu_cohort_new$insurance,
           ethnicity = icu_cohort_new$ethnicity,
           age = icu_cohort_new$age,
           Systolic_BP = icu_cohort_new$Systolic_BP,
           Diastolic_BP = icu_cohort_new$Diastolic_BP,
           Resp_rate = icu_cohort_new$Resp_rate,
           Heart_rate = icu_cohort_new$Heart_rate,
           Temperature = icu_cohort_new$Temperature,
           admission_type = icu_cohort_new$admission_type
    )
  })
  
  output$view <- renderTable({
    if (input$Variable %in% names(icu_cohort_new)) {
      head(datasetInput(), n = input$obs)
    }
  })
  
  output$summary <- renderTable({
    if(input$Variable %in% names(icu_cohort_new)){
      data <- datasetInput()
      if(input$indicator == "0"){
        data_summary <- data %>% 
          group_by(!!sym(input$Variable)) %>% 
          summarize(n = n()) %>% 
          mutate(prop = n/sum(n))
      } else {
        data_summary <- data %>% 
          group_by(!!sym(input$Variable), thirty_day_mortality) %>% 
          summarize(n = n()) %>% 
          mutate(prop = n/sum(n)) %>% 
          select(-n) %>% 
          spread(thirty_day_mortality, prop)
      }
      data_summary
    }
  })
}


shinyApp(ui, server)

```



```{r}

# test out plots for some other variables
library(dplyr)


ui <- fluidPage(

  # App title ----
  titlePanel("Saanchi's icu cohort"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Selector for variable to plot against mpg ----
      selectInput("variable", "Variable:",
                  choices = c(Hematocrit = "Hematocrit" ,
                              Chloride = "Chloride" ,
                              Sodium = "Sodium")),


      # Input: Checkbox for whether outliers should be included ----
      checkboxInput("outliers", "Show outliers", TRUE)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Formatted text for caption ----
      h3(textOutput("caption")),

      # Output: Plot of the requested variable against mpg ----
      plotOutput("mortPlot")

    )
  )
)


server <- function(input, output) {

  # Compute the formula text ----
  # This is in a reactive expression since it is shared by the
  # output$caption and output$mpgPlot functions
  formulaText <- reactive({
    paste("thirty_day_mortality ~", input$variable)
  })

  # Return the formula text for printing as a caption ----
  output$caption <- renderText({
    formulaText()
  })

  

  # Generate a plot of the requested variable against mpg ----
  # and only exclude outliers if requested
  output$mortPlot <- renderPlot({
   # formula <- as.formula(paste("thirty_day_mortality ~", input$variable)) # I am not getting box plots, help
    # boxplot(formula, data = icu_cohort_new, outline = input$outliers)
    ggplot(data = icu_cohort_new) +
      geom_point(mapping = aes_string(x = "thirty_day_mortality", y = input$variable))
  })
}



shinyApp(ui, server)
```


```{r}
server <- function(input, output) {
  output$boxplot <- renderPlot({
    formula <- as.formula(paste("thirty_day_mort ~", input$variable))
    boxplot(formula, data = icu_cohort, outline = input$outliers)
  })
}
```

```{r}
server <- function(input, output){
  output$table <- renderTable({
    if(input$var %in% icu_cohort_new){
      if(input$indicator == 0){
        data %>% 
          group_by_(input$var) %>% 
          summarize(n = n()) %>% 
          mutate(prop = n/sum(n))
      } else {
        data %>% 
          group_by_("thirty_day_mort", input$var) %>% 
          summarize(n = n()) %>% 
          select(-n) %>% 
          spread("thirty_day_mort", prop)
      }
      }
      }
    }
  })
}
```

